Retry the read

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -50,7 +50,11 @@ fi
 echo "** TCP/22 forwarding..."
 ip=$(lstack ip)
 lstack forward test 22
-read -r ssh_ok < /dev/tcp/$ip/22
+# may not be ready, retry
+read -r ssh_ok < /dev/tcp/$ip/22 || {
+  sleep 2
+  read -r ssh_ok < /dev/tcp/$ip/22
+}
 if ! [[ "$ssh_ok" =~ dropbear ]]; then
   >&2 echo "SSH forward test (instance) failed!"
   exit 1
