Added forward command

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -39,7 +39,23 @@ for i in $(seq 1 10); do
   sleep 5
 done
 if [ -z "$ssh_ok" ]; then
-  >&2 SSH test failed!
+  >&2 echo Cirros instance SSH test failed!
+  exit 1
+fi
+
+# Test 22 port forward
+ssh_ok=""
+lstack forward test 22
+echo | nc $(lstack ip) 22 | grep dropbear > /dev/null && ssh_ok=1
+if [ -z "$ssh_ok" ]; then
+  >&2 echo "SSH forward test (instance) failed!"
+  exit 1
+fi
+
+ssh_ok=""
+echo | nc $(lstack ip) 2200 | grep OpenSSH > /dev/null && ssh_ok=1
+if [ -z "$ssh_ok" ]; then
+  >&2 echo "SSH forward test (container) failed!"
   exit 1
 fi
 
